#!/usr/bin/python3

from downcast.server import DWCDB
from downcast.extractor import (Extractor, WaveSampleQueue, NumericValueQueue,
                                EnumerationValueQueue, AlertQueue,
                                PatientMappingQueue, PatientBasicInfoQueue,
                                PatientDateAttributeQueue,
                                PatientStringAttributeQueue, BedTagQueue)
from downcast.timestamp import T

class TestHandler():
    def send_message(self, channel, message, source, ttl):
        print('%s\t%s\t%s' % (message.timestamp, channel,
                              type(message).__name__))
        source.ack_message(channel, message, self)

DWCDB.load_config('server.conf')
db = DWCDB('demo')
ex = Extractor(db, '/tmp/downcast-extractor-test', fatal_exceptions = True)

ex.add_handler(TestHandler())

st = None
ex.add_queue(WaveSampleQueue('waves', start_time = st,
                             messages_per_batch = 10))
ex.add_queue(NumericValueQueue('numerics', start_time = st,
                               messages_per_batch = 10))
ex.add_queue(EnumerationValueQueue('enums', start_time = st,
                                   messages_per_batch = 10))
ex.add_queue(AlertQueue('alerts', start_time = st,
                        messages_per_batch = 10))
ex.add_queue(PatientMappingQueue('mapping', start_time = st,
                                 messages_per_batch = 10))
ex.add_queue(PatientBasicInfoQueue('patients', start_time = st,
                                   messages_per_batch = 10))
ex.add_queue(PatientStringAttributeQueue('strings', start_time = st,
                                         messages_per_batch = 10))
ex.add_queue(PatientDateAttributeQueue('dates', start_time = st,
                                       messages_per_batch = 10))
ex.add_queue(BedTagQueue('beds', start_time = st,
                         messages_per_batch = 10))

for _ in range(100):
    ex.run()
