#!/usr/bin/python3

import shutil
from datetime import timedelta

from downcast.server import DWCDB
from downcast.extractor import (Extractor, WaveSampleQueue, NumericValueQueue,
                                EnumerationValueQueue, AlertQueue,
                                PatientMappingQueue, PatientBasicInfoQueue,
                                PatientStringAttributeQueue,
                                PatientDateAttributeQueue)
from downcast.timestamp import T
from downcast.output.archive import Archive
from downcast.output.numerics import NumericValueHandler
from downcast.output.waveforms import WaveSampleHandler
from downcast.output.mapping import PatientMappingHandler
from downcast.output.patients import PatientHandler

DWCDB.load_config('server.conf')

def test(dest_dir, iterations):
    db = DWCDB('demo')
    ex = Extractor(db, dest_dir, fatal_exceptions = True)
    arx = Archive(dest_dir)
    nh = NumericValueHandler(arx)
    ex.add_handler(nh)
    mh = PatientMappingHandler(arx)
    ex.add_handler(mh)
    ph = PatientHandler(arx)
    ex.add_handler(ph)
    wh = WaveSampleHandler(arx)
    ex.add_handler(wh)

    pmq = PatientMappingQueue('mapping')
    pmdelay = timedelta(minutes = 30)
    ex.add_queue(pmq)

#    ex.add_queue(PatientBasicInfoQueue('patients'))
#    ex.add_queue(PatientStringAttributeQueue('strings'))
#    ex.add_queue(PatientDateAttributeQueue('dates'))

    st = T('2016-01-28 14:00:00.000 -05:00')
#    ex.add_queue(NumericValueQueue('numerics', start_time = st,
#                                   messages_per_batch = 100,
#                                   patient_mapping_queue = pmq,
#                                   patient_mapping_delay = pmdelay))
    ex.add_queue(WaveSampleQueue('waves', start_time = st,
                                 messages_per_batch = 100,
                                 patient_mapping_queue = pmq,
                                 patient_mapping_delay = pmdelay))
    for _ in range(iterations):
        ex.run()
    ex.flush()

shutil.rmtree('/tmp/downcast-extractor-test', ignore_errors = True)
test('/tmp/downcast-extractor-test', 5)
test('/tmp/downcast-extractor-test', 5)
test('/tmp/downcast-extractor-test', 5)
test('/tmp/downcast-extractor-test', 5)

shutil.rmtree('/tmp/downcast-extractor-test2', ignore_errors = True)
test('/tmp/downcast-extractor-test2', 20)
