#!/usr/bin/python3

import shutil

from server import DWCDB
from extractor import (Extractor, WaveSampleQueue, NumericValueQueue,
                       EnumerationValueQueue, AlertQueue)
from timestamp import T
from output.archive import Archive
from output.numerics import NumericValueHandler

DWCDB.load_config('server.conf')

def test(dest_dir, iterations):
    db = DWCDB('demo')
    ex = Extractor(db, dest_dir, fatal_exceptions = True)
    arx = Archive(dest_dir)
    nh = NumericValueHandler(arx)
    ex.add_handler(nh)

    st = T('2016-01-28 14:00:00.000 -05:00')
    ex.add_queue(NumericValueQueue('numerics', start_time = st,
                                   messages_per_batch = 100))
    for _ in range(iterations):
        ex.run()
    ex.flush()

shutil.rmtree('/tmp/downcast-extractor-test', ignore_errors = True)
test('/tmp/downcast-extractor-test', 5)
test('/tmp/downcast-extractor-test', 5)
test('/tmp/downcast-extractor-test', 5)
test('/tmp/downcast-extractor-test', 5)

shutil.rmtree('/tmp/downcast-extractor-test2', ignore_errors = True)
test('/tmp/downcast-extractor-test2', 20)
